# -*- coding: utf-8 -*-
"""JinaAI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vHZIBjtUmCoTo5Oj-HXWdfJwmMdFmRn0
"""

!pip install jina

"""A simple image neural search demo for Fashion-MNIST. No extra dependencies needed"""

!jina hello --help

"""For NLP engineers, it provide a simple chatbot demo for answering Covid-19 questions

This downloads CovidQA dataset and tells Jina to index 418 question-answer pairs with MPNet. The index process takes about 1 minute on CPU. Then it opens a web page where you can input questions and ask Jina.
"""

!jina hello fashion

import IPython
IPython.display.HTML(filename='/content/9fad3428-9979-4ca1-a8c6-d8e11cfb500c/demo.html')

!pip install "jina[chatbot]"

!jina hello chatbot

import IPython
IPython.display.HTML(filename='/content/895d1c0c-5e77-4c90-8b2a-7469eb376cf5/MyIndexer/0/indexer/header.bin')

!pip install "jina[multimodal]"

!jina hello multimodal

import IPython
IPython.display.HTML(filename='/content/b3e2dc0a-0325-4d98-9a01-762d117ad5ca')